var userName = prompt('Ismingiz nima? ')
var userAge = +prompt('Yoshingiz nechida? ')
console.info ('Sizning ismingiz ' + userName  + ' / Sizning yoshingiz ' + userAge + ' da!')
var plus = +prompt('6 + 8 = ')
alert('Sizning javobingiz - ' + plus + ' / To"g"ri javob:  6 + 8 = 14')
var minus = +prompt('76 - 23 = ')
alert('Sizning javobingiz - ' + minus + ' / To"g"ri javob:  76 - 23 = 53')
var kopay = +prompt('12 * 3 = ')
alert('Sizning javobingiz - ' + kopay + ' / To"g"ri javob:  12 * 3 = 36')
var bol = +prompt('33 / 11 = ')
alert('Sizning javobingiz - ' + bol + ' / To"g"ri javob:  33 / 11 = 3')
var qoldiq = +prompt('45 % 4 = ')
alert('Sizning javobingiz - ' + qoldiq + ' / To"g"ri javob:  45 % 4 = 1')
var daraja = +prompt('2 ** 4 = ')
alert('Sizning javobingiz - ' + daraja + ' / To"g"ri javob:  2 ** 4 = 16')
var tochka = +prompt('10 / 3 = ')
alert('Sizning javobingiz - ' + tochka + ' / To"g"ri javob:  10 / 3 = 3.33333333')
var info = 'Sizning javoblaringiz:'
console.info(plus, minus, kopay, bol, qoldiq, daraja, tochka)